@Library("jenlib") _

try {
	runOnSlave(label: "frontend") {
		cleanWs()
	}

	inSingularity(app: "visionary-dls") {
		stage('Checkout') {
			runOnSlave(label: "frontend") {
				wafSetup(projects: ["binutils-gdb@binutils-2_25-branch-nux", "gcc@gcc-8_1-branch-nux"])
				sish "bash gcc/ci/00_download_prerequisites.sh"
			}
		}

		stage("Build") {
			onSlurmResource(partition: "jenkins", "cpus-per-task": "8") {
				sish "bash binutils-gdb/ci/00_build_install_eabi.sh"
				sish "bash gcc/ci/01_build_install_freestanding.sh"
			}
		}
	}

} catch (Throwable t) {
	notifyFailure(mattermostChannel: "#dls-software")
        throw t
} finally {
	// Always clean the workspace
	runOnSlave(label: "frontend") {
		cleanWs()
	}
}

// Some Jenkins steps fail a build without raising (e.g. archiveArtifacts)
if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#dls-software")
}
